### PR TITLE
spreadsheet interface for bliplay

### PR DESCRIPTION
**Pull request by mgarcia-org**
python 2 script to convert csv to blip and example of test6.blip in a simple spreadsheet

### CODE REVIEW

**Comment by detomon** [comment]
Very interesting. I like the idea how you want to implement a "pattern editor" using a spreadsheet and then auto-compile the output.

But I think that should be a separate project, maybe you want to create your own repo for this. I will then add the link and description to your project in the README.

_Additional question: You mentioned high CPU usage in "log & info" while playing the files. Does this also happen when playing the files normally, for example, `bliplay out.blip`? If so, this could be a bug and I have to look into that._

**Comment by mgarcia-org** [comment]
Cool, good idea!
re CPU usage, I'm not 100% sure, I'd say it's a my hacky shell script spreadsheet-interface.sh, with inotifywait.
I'll fix it and set up a repo for it.
Cheers
Mike.

**Comment by mgarcia-org** [comment]
https://github.com/mgarcia-org/blipSheet
I couldn't figure out the high cpu usage, so I made it output to wav and get mplayer to loop it.
Also did a quick video, how I use it and debug errors etc.

**Comment by detomon** [comment]
Neat, I added your project to the README: https://github.com/detomon/bliplay/blob/master/README.md#6-related-projects.

**Pull request closed without merging**
